name: Create Release and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Bump version and create tag
        id: bump_version
        run: |
          NEW_VERSION=$(npm version patch -m "chore(release): %s")
          echo "NEW_VERSION=${NEW_VERSION/v/}" >> $GITHUB_ENV
          echo "::set-output name=new_version::${NEW_VERSION/v/}"
          git push --follow-tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          release_name: Release ${{ steps.bump_version.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: ./packages/docs
        run: |
          touch storybook-static/.nojekyll
          npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
